---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    # Use the second interface (first non-NAT interface in VirtualBox)
    molecule_interface: "{{ ansible_interfaces | reject('equalto', 'lo') | list | last }}"
    molecule_ip: "{{ hostvars[inventory_hostname]['ansible_' + molecule_interface]['ipv4']['address'] }}"
    molecule_network: "{{ molecule_ip | regex_replace('\\.[0-9]+$', '') }}"
  roles:
    - role: ansible-role-dnsmasq
      vars:
        dnsmasq_interface: "{{ molecule_interface }}"
        dnsmasq_domain: test.local
        dhcp_range_start: "{{ molecule_network }}.100"
        dhcp_range_end: "{{ molecule_network }}.200"
        dhcp_lease_time: 1h
        dhcp_option_router: "{{ molecule_network }}.1"
        dhcp_option_dns: "{{ molecule_ip }}"
        upstream_dns:
          - 8.8.8.8
