---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ubuntu-jammy
    box: ubuntu/jammy64
    memory: 1024
    cpus: 1
    interfaces:
      - network_name: private_network
        type: dhcp

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: testinfra
